# -*- coding: utf-8 -*-
"""treino.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11EfsI5sGSKIhLAwhmNy68aSrxeaNfr0S
"""

from sklearn.naive_bayes import GaussianNB
import pandas as pd
url = "car.csv"
data = pd.read_csv(url)
data.info()
data.head()

x = data.drop('class', axis=1)#features
y = data['class']#label
print(y)

from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y, test_size=0.3, random_state=40)

clf = GaussianNB()
clf = clf.fit(x_treino, y_treino)
preditos = clf.predict(x_teste)
real = y_teste.values
print("Preditos: ", preditos[:20])
print("Real....: ", real[:20])

from sklearn.metrics import accuracy_score

print("Acuracia: ")

print(f"Acurácia de Treino: {round(accuracy_score(preditos, real), 2)}")
print('\n ---------------------------\n')

import pickle 
pickle.dump(clf, open('modelo.pkl', 'wb'))